INSERT INTO customers (name, address, neighborhood, customer_type, needs_review, review_reason) VALUES
('Caco Israel', 'Zapiola 860', NULL, 'minorista', false, NULL),
('Cirilo Rolotti', 'Palestina 1190', NULL, 'minorista', false, NULL),
('Juanse Castillo', 'Tamborini 2626', NULL, 'minorista', false, NULL),
('Leila Armini', 'Virrey del Pino 3454', NULL, 'minorista', false, NULL),
('Tiago Serrago', 'Libertador 3042', NULL, 'minorista', false, NULL),
('Nicolas Armini', 'Cabrera 5052', NULL, 'minorista', false, NULL),
('Julieta Allassia', 'Federico Lacroze 1955, 6 "4"', NULL, 'minorista', false, NULL),
('Facundo Vito', 'Olazábal 1340', NULL, 'minorista', false, NULL),
('Marcelo Armini', 'Av. Los Incas 5349', NULL, 'minorista', false, NULL),
('Esteban', 'Av. de los Incas 5133', NULL, 'minorista', true, 'Falta apellido'),
('Malena Mora', 'Conesa 2267', NULL, 'minorista', false, NULL),
('Gonzalo Vazquez', 'Honduras 4043', NULL, 'minorista', false, NULL),
('Cecilia Iglesias', 'Ramsay 2055 piso 1 05', NULL, 'minorista', false, NULL),
('Gonzalo Armini', 'Cabrera 5052', NULL, 'minorista', false, NULL),
('Martin Yahia', 'Rafael Hernandez 2721', NULL, 'minorista', false, NULL),
('Ariel Alumni', 'Campo Grande, Pilar', NULL, 'minorista', false, NULL),
('Gonzalo Alumni', 'Las Amapolas 1001, depto B08, Los Malvones, Pilar', NULL, 'minorista', false, NULL),
('Fer Alumni', 'Barrio Galapagos, lote 135', NULL, 'minorista', false, NULL),
('Juan Alumni', 'Barrio La Montura, Manuel Alberti', NULL, 'minorista', false, NULL),
('Paola (Papa)', 'A completar', NULL, 'minorista', true, 'Cliente de Papa (Juan Cruz) — falta nombre completo y dirección'),
('Carlos (Papa)', 'A completar', NULL, 'minorista', true, 'Cliente de Papa (Juan Cruz) — falta nombre completo y dirección'),
('Chris (Papa)', 'A completar', NULL, 'minorista', true, 'Cliente de Papa (Juan Cruz) — falta nombre completo y dirección'),
('Gonzalo Benavidez', 'Av. Alvear 801, Barrio Valle Claro lote 86', NULL, 'minorista', false, NULL),
('Meme Agusto', 'Arenales 2329 Piso 8', NULL, 'minorista', false, NULL),
('Santiago Sasso', 'Gorriti 4091', NULL, 'minorista', false, NULL),
('Cintia Dominguez', 'Tamborini 2626', NULL, 'minorista', false, NULL),
('Josefina Murgu', 'Ayacucho 1145 9B', NULL, 'minorista', false, NULL),
('Julio Libertador', 'Av. Libertador 3810 P8', NULL, 'minorista', false, NULL),
('Facundo Ale', 'Araoz 2445', NULL, 'minorista', false, NULL),
('Fran Mattos', 'Palermo', 'Palermo', 'minorista', true, 'Falta calle y altura de la dirección'),
('Mauro PP', 'Tamborini 4385', NULL, 'minorista', false, NULL),
('Martin (Papa)', 'A completar', NULL, 'minorista', true, 'Cliente de Papa (Juan Cruz) — falta nombre completo y dirección'),
('Papa', 'A completar', NULL, 'minorista', true, 'Cliente sin identificar — completar nombre y dirección'),
('Santiago Belgrano', '11 de Septiembre 832, 8vo C', NULL, 'minorista', false, NULL),
('Bruno Piramides', 'Av. San Isidro Labrador 4166 1 D', NULL, 'minorista', false, NULL),
('Bocha Piramides', 'Lavalle 4050 23 B Torre 1', NULL, 'minorista', false, NULL);
